### ISSUE TITLE
Create an interface for LOC api servers

### ISSUE THREAD

**Issue by rickzx98** [great-design-and-systems/cataloguing-module#7]
Create a restful interface for the following:

- Library of Congress Online Catalog
- National Library Service for the Blind and Physically Handicapped
- Handbook of Latin American Studies
- Library of Congress Name Authority File
- Library of Congress Subject Authority File

For server endpoints go to  https://www.loc.gov/standards/sru/resources/lcServers.html

In this interface i should be able to:
- query any items by title, author, isbn, lccn, or any identifiers
- skip items (startIndex)
- limit the result
- choose which server to use

The response should be in JSON format.
See the old cataloging service project for reference.
Please finish this within the week. Aug 8, 2017 - Aug 13, 2017

**Comment by analynf** [comment]
Use the following url:
http://localhost/api/search-online/:source?queryparam
where :source is LCDB, NLSBPH, HLAS, NAF or SAF

for other SRU, just add the url to sru.list file
